### ISSUE TITLE
Invalid Dockerfile

### ISSUE THREAD

**Issue by marines** [mhzawadi/invoiceplane#2]
The sed doesn't set the variables properly. `ipconfig.php` isn't being evaluated by PHP so `getenv()` is just a string instead of a function invocation. This makes docker put invalid values there.

**Comment by mhzawadi** [comment]
Thanks @marines for this, will re-work the config file with some code I have else where

**Comment by mhzawadi** [comment]
@marines have pushed v1.5.10.2 that should fix your issue, please close this if it does.

**Comment by marines** [comment]
Now the `ipconfig.php` file is owned by root so the setup cannot proceed. That's assuming manual setup is intended. I reckon you may want to set `SETUP_COMPLETED=true` but then I guess also the `ENCRYPTION_KEY` should be set manually since setup deals with that.

**Comment by mhzawadi** [comment]
will have a look and see if I can sort

**Comment by mhzawadi** [comment]
have updated the start script to set the owner of the config file, it looks to work as planned now

**Comment by jake-walker** [comment]
I'm having trouble with the config file being overwritten when restarting the container. I have a volume on my container that persists the `ipconfig.php` file to the local disk with `-v /path/to/ipconfig.php:/var/www/html/ipconfig.php`.

When the container boots up, the `start.sh` script performs `sed` on the sample config and then overwrites the config that I have persisted.

https://github.com/mhzawadi/invoiceplane/blob/2f803deff444c2ef1071977cf53c2a6ac6b859c4/setup/start.sh#L16

I think this could be fixed by deleting the `ipconfig.php` in the Dockerfile and then checking whether the file exists before overwriting in `start.sh`. I'll have a look at making a PR.
