### ISSUE TITLE
v1.6.0 php dom missing?

### ISSUE THREAD

**Issue by artanko** [mhzawadi/invoiceplane#33]
* **I'm submitting a ...**
  - [ x] bug report
  - [ ] feature request

* ** please explain your *feature* or *bug* report**

php dom is missing

* **What is the current behavior?**
when sending an invoice which include zugferd xml the error 'class 'DOMDocument' not found' pops up

* **What is the expected behavior?**
mail being sent without error
  
  - Version: 1.6.0
  - Browser: all
  - Language: all

thx for the image ,  great work

**Comment by mhzawadi** [comment]
Hello 👋🏼 

Thanks for your bug report, having looked at the [InvoicePlane](https://github.com/InvoicePlane/InvoicePlane) github issues. This could be a bug, they have 2 issues for zugferd xml

- https://github.com/InvoicePlane/InvoicePlane/issues/912
- https://github.com/InvoicePlane/InvoicePlane/issues/913

Will have to wait and see if they get fixed in version 1.6.2, when every that gets releases

**Comment by mhzawadi** [comment]
Thanks @powellcn for your PR, merged and new image builds underway

**Comment by powellcn** [comment]
@mhzawadi    incredibly fast!   Glad to have helped.
